config/routes.rb
Rails.application.routes.draw do
  
  

  get 'sessionartists/new'

  get 'sessions/new'

  get 'artists/new'

  root 'static_pages#home'
  
  get 'signup_users' => 'users#new' 
  
  get 'signup_artists' => 'artists#new'
  
  get 'help' => 'static_pages#help'

  get 'contact_us' => 'static_pages#contact_us'

  get 'about' => 'static_pages#about'

  get 'advice' => 'static_pages#advice'

  get 'search_results' => 'static_pages#search_result'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get    'login_artist'   => 'sessionartists#new'
  post   'login_artist'   => 'sessionartists#create'
  delete 'logout_artist'  => 'sessionartists#destroy'
  resources :artists
  resources :users

  
  
  resources :users
  resources :artists

  
end

app/models/artist.rb
class Artist < ActiveRecord::Base
    attr_accessor :remember_token
    
    before_save { self.email = email.downcase }
    validates :name, length: { maximum: 100 } , presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, length: { maximum: 250 } , presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

    #validates :password, length: { maximum: 100 } , presence: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    validates :gravatar_url, length: { maximum: 2083 }
    validates :description, length: { maximum: 200 } 
    
    validates :skill, length: { maximum: 200 } 
    validates :experience, length: { maximum: 200 }
 
    validates :facebook_url, length: { maximum: 2083 }
    validates :twitter_url, length: { maximum: 2083 }
    validates :contact_no, length: { maximum: 15 }
    validates :address, length: { maximum: 300 }
    validates :country, length: { maximum: 100 }
    validates :state, length: { maximum: 100 }
    validates :city, length: { maximum: 100 }
    validates :availability, length: { maximum: 100 }
    validates :youtube_url, length: { maximum: 2083 }
    validates :behance_url, length: { maximum: 2083 }
    validates :facebook_page, length: { maximum: 2083 }
    validates :blog_url, length: { maximum: 2083 }
    validates :website_url, length: { maximum: 2083 }
    validates :other_url, length: { maximum: 2083 }
    validates :motto_line, length: { maximum: 200 }
    
    # Returns the hash digest of the given string.
  def Artist.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def Artist.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  #def remember
   # self.remember_token = Artist.new_token
    #update_attribute(:remember_digest, Artist.digest(remember_token))
  #end
  
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  
  def show
    @artist = Artist.find(params[:id])
  end


  
  def new
    @artist = Artist.new
  end
  
  def create
    @artist = Artist.new(artist_params)    # Not the final implementation!
    if @artist.save
      # Handle a successful save.
      login_artist @artist
      flash[:success] = "Welcome to the Artisto!"
      redirect_to @artist
    else
      render 'new'
    end
  end
  
  private

    def artist_params
      params.require(:artist).permit(:name, :email, :password,
                                   :password_confirmation, :gravatar_url, :description, :skill, :experience, 
                                   :facebook_url, :twitter_url , :contact_no, :address, :country, :state, :city, 
                                   :availability, :youtube_url, :behance_url , :facebook_page, :blog_url, :website_url, :other_url , :motto_line)
    end


end

app/helpers/artists_helper.rb
module ArtistsHelper
    # Returns the Gravatar for the given user.
  def gravatar_for(artist)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: artist.name, class: "gravatar")
  end

end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :gravatar_url %><br>
    <%= f.text_field :gravatar_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :skill %><br>
    <%= f.text_field :skill %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.number_field :experience %>
  </div>
  <div class="field">
    <%= f.label :facebook_url %><br>
    <%= f.text_field :facebook_url %>
  </div>
  <div class="field">
    <%= f.label :twitter_url %><br>
    <%= f.text_field :twitter_url %>
  </div>
  <div class="field">
    <%= f.label :contact_no %><br>
    <%= f.text_field :contact_no %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :availability %><br>
    <%= f.text_field :availability %>
  </div>
  <div class="field">
    <%= f.label :youtube_url %><br>
    <%= f.text_field :youtube_url %>
  </div>
  <div class="field">
    <%= f.label :behance_url %><br>
    <%= f.text_field :behance_url %>
  </div>
  <div class="field">
    <%= f.label :facebook_page %><br>
    <%= f.text_field :facebook_page %>
  </div>
  <div class="field">
    <%= f.label :blog_url %><br>
    <%= f.text_field :blog_url %>
  </div>
  <div class="field">
    <%= f.label :website_url %><br>
    <%= f.text_field :website_url %>
  </div>
  <div class="field">
    <%= f.label :other_url %><br>
    <%= f.text_field :other_url %>
  </div>
  <div class="field">
    <%= f.label :motto_line %><br>
    <%= f.text_area :motto_line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Gravatar url</th>
      <th>Description</th>
      <th>Skill</th>
      <th>Experience</th>
      <th>Facebook url</th>
      <th>Twitter url</th>
      <th>Contact no</th>
      <th>Address</th>
      <th>Country</th>
      <th>State</th>
      <th>City</th>
      <th>Availability</th>
      <th>Youtube url</th>
      <th>Behance url</th>
      <th>Facebook page</th>
      <th>Blog url</th>
      <th>Website url</th>
      <th>Other url</th>
      <th>Motto line</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.email %></td>
        <td><%= artist.password %></td>
        <td><%= artist.gravatar_url %></td>
        <td><%= artist.description %></td>
        <td><%= artist.skill %></td>
        <td><%= artist.experience %></td>
        <td><%= artist.facebook_url %></td>
        <td><%= artist.twitter_url %></td>
        <td><%= artist.contact_no %></td>
        <td><%= artist.address %></td>
        <td><%= artist.country %></td>
        <td><%= artist.state %></td>
        <td><%= artist.city %></td>
        <td><%= artist.availability %></td>
        <td><%= artist.youtube_url %></td>
        <td><%= artist.behance_url %></td>
        <td><%= artist.facebook_page %></td>
        <td><%= artist.blog_url %></td>
        <td><%= artist.website_url %></td>
        <td><%= artist.other_url %></td>
        <td><%= artist.motto_line %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@artist) do |f| %>
      <%= render 'shared/error_messages_artists' %>


      
      <%= f.label :name %>
      <%= f.text_field :name , class: 'form-control'%>

      <%= f.label :email  %>
      <%= f.email_field :email , class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password , class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation , class: 'form-control' %>
      
      <%= f.label :description %>
      <%= f.text_field :description , class: 'form-control' %>
      
      <%= f.label :skill %>
      <%= f.text_field :skill , class: 'form-control' %>
      
      <%= f.label :experience %>
      <%= f.number_field :experience , class: 'form-control' %>
      
      <%= f.label :facebook_url %>
      <%= f.url_field :facebook_url , class: 'form-control' %>
      
      <%= f.label :twitter_url %>
      <%= f.url_field :twitter_url , class: 'form-control' %>
      
      <%= f.label :contact_no %>
      <%= f.telephone_field :contact_no , class: 'form-control' %>
      
      <%= f.label :address %>
      <%= f.text_field :address , class: 'form-control' %>
      
      <%= f.label :country %>
      <%= f.text_field :country , class: 'form-control' %>
      
      <%= f.label :state %>
      <%= f.text_field :state , class: 'form-control' %>
      
      <%= f.label :city %>
      <%= f.text_field :city , class: 'form-control' %>
      
      <%= f.label :availability %>
      <%= f.text_field :availability , class: 'form-control' %>
      

      <%= f.label :youtube_url %>
      <%= f.url_field :youtube_url , class: 'form-control' %>
      
      <%= f.label :behance_url %>
      <%= f.url_field :behance_url , class: 'form-control' %>
      
      <%= f.label :facebook_page %>
      <%= f.url_field :facebook_page , class: 'form-control' %>
      
      <%= f.label :blog_url %>
      <%= f.url_field :blog_url , class: 'form-control' %>
      
      <%= f.label :website_url %>
      <%= f.url_field :website_url , class: 'form-control' %>
      
      <%= f.label :other_url %>
      <%= f.url_field :other_url , class: 'form-control' %>
      
      <%= f.label :motto_line %>
      <%= f.text_field :motto_line , class: 'form-control' %>
      




      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/artists/show.html.erb
<% provide(:title, @artist.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @artist %>
        <%= @artist.name %>
      </h1>
    </section>
  </aside>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @artist.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @artist.password %>
</p>

<p>
  <strong>Gravatar url:</strong>
  <%= @artist.gravatar_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artist.description %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @artist.skill %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @artist.experience %>
</p>

<p>
  <strong>Facebook url:</strong>
  <%= @artist.facebook_url %>
</p>

<p>
  <strong>Twitter url:</strong>
  <%= @artist.twitter_url %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @artist.contact_no %>
</p>

<p>
  <strong>Address:</strong>
  <%= @artist.address %>
</p>

<p>
  <strong>Country:</strong>
  <%= @artist.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @artist.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @artist.city %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @artist.availability %>
</p>

<p>
  <strong>Youtube url:</strong>
  <%= @artist.youtube_url %>
</p>

<p>
  <strong>Behance url:</strong>
  <%= @artist.behance_url %>
</p>

<p>
  <strong>Facebook page:</strong>
  <%= @artist.facebook_page %>
</p>

<p>
  <strong>Blog url:</strong>
  <%= @artist.blog_url %>
</p>

<p>
  <strong>Website url:</strong>
  <%= @artist.website_url %>
</p>

<p>
  <strong>Other url:</strong>
  <%= @artist.other_url %>
</p>

<p>
  <strong>Motto line:</strong>
  <%= @artist.motto_line %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>