config/routes.rb
Rails.application.routes.draw do
  
  

  get 'sessionartists/new'

  get 'sessions/new'

  get 'artists/new'

  root 'static_pages#home'
  
  get 'signup_users' => 'users#new' 
  
  get 'signup_artists' => 'artists#new'
  
  get 'help' => 'static_pages#help'

  get 'contact_us' => 'static_pages#contact_us'

  get 'about' => 'static_pages#about'

  get 'advice' => 'static_pages#advice'

  get 'search_results' => 'static_pages#search_result'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get    'login_artist'   => 'sessionartists#new'
  post   'login_artist'   => 'sessionartists#create'
  delete 'logout_artist'  => 'sessionartists#destroy'
  resources :artists
  resources :users

  
  
  resources :users
  resources :artists

  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "About Us",   about_path %></li>
            <li><%= link_to "Contact Us",   contact_us_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Facebook",   '#' %></li>
            <li><%= link_to "Twitter",   '#' %></li>
            <li><%= link_to "YouTube",   '#' %></li>
          </ul>
        </nav>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to ":Artisto", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Current Location",   '#' %></li>
            <li><%= link_to "Advice", '#' %></li>
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
            </li>
          <% elsif logged_in_artist?  %>
            <li><%= link_to "Artists", '#' %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_artist %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_artist_path, method: "delete" %>
              </li>
            </ul>
            </li>
            <% else %>
           <li><%= link_to "Log in", login_path %></li>
           <li><%= link_to "Register", signup_users_path %></li>
           <li><%= link_to "Log in for Artists", login_artist_path %></li>
           <li><%= link_to "Register for Artists", signup_artists_path %></li>
        
        <% end %>
        
        
            
            </li>
          </ul>
        </nav>
      </div>
    </header>
    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <%= render 'layouts/shim' %>
   </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug( params ) if Rails.env.development? %>
    </div>
    
  </body>
</html>